"""Shared helpers for VisionOps v3 training pipeline."""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any, TextIO

try:
    import yaml
except Exception:  # pragma: no cover
    yaml = None  # type: ignore[assignment]

IMAGE_EXTS = {".jpg", ".jpeg", ".png", ".bmp", ".webp"}


@dataclass
class PipelineContext:
    project_root: Path
    job: dict[str, Any]
    dataset: dict[str, Any]
    job_dir: Path
    work_dir: Path
    output_dir: Path
    log_file: TextIO | None = None

    def log(self, message: str) -> None:
        line = f"{time.strftime('%Y-%m-%d %H:%M:%S')} {message}"
        if self.log_file is not None:
            self.log_file.write(line + "\n")
            self.log_file.flush()
        else:  # pragma: no cover
            print(line, flush=True)


def read_json(path: Path, default: Any = None) -> Any:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return default


def write_json(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def read_yaml(path: Path, default: Any = None) -> Any:
    if not path.exists():
        return default
    text = path.read_text(encoding="utf-8")
    if yaml is not None:
        try:
            return yaml.safe_load(text)
        except Exception:
            return default
    return _simple_yaml_load(text, default)


def write_yaml(path: Path, value: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if yaml is not None:
        class _NoAliasDumper(yaml.SafeDumper):
            def ignore_aliases(self, data):  # type: ignore[no-untyped-def]
                return True

        path.write_text(
            yaml.dump(value, Dumper=_NoAliasDumper, allow_unicode=True, sort_keys=False),
            encoding="utf-8",
        )
    else:
        path.write_text(json.dumps(value, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def _simple_yaml_load(text: str, default: Any = None) -> Any:
    """Very small YAML reader for data.yaml/model.yaml fallback.

    It intentionally supports only the structures generated by this pipeline.
    """
    result: dict[str, Any] = {}
    lines = text.splitlines()
    i = 0
    while i < len(lines):
        raw = lines[i]
        line = raw.rstrip()
        if not line.strip() or line.lstrip().startswith("#"):
            i += 1
            continue
        if line.startswith("names:"):
            names: dict[int, str] = {}
            i += 1
            while i < len(lines) and (lines[i].startswith("  ") or lines[i].startswith("-")):
                item = lines[i].strip()
                if ":" in item:
                    k, v = item.split(":", 1)
                    try:
                        names[int(k.strip().strip("'\""))] = v.strip().strip("'\"")
                    except Exception:
                        pass
                elif item.startswith("-"):
                    names[len(names)] = item[1:].strip().strip("'\"")
                i += 1
            result["names"] = names
            continue
        if ":" in line:
            key, value = line.split(":", 1)
            result[key.strip()] = value.strip().strip("'\"")
        i += 1
    return result or default


def list_images(images_dir: Path) -> list[Path]:
    if not images_dir.exists():
        return []
    return sorted(p for p in images_dir.iterdir() if p.is_file() and p.suffix.lower() in IMAGE_EXTS)


def safe_id(value: str) -> str:
    text = str(value or "").strip().replace(" ", "_")
    safe = "".join(ch for ch in text if ch.isalnum() or ch in {"_", "-", "."})
    if not safe or safe in {".", ".."}:
        raise ValueError("非法 ID")
    return safe


def normalize_task(task_type: str | None) -> str:
    task = str(task_type or "detection").strip().lower()
    if task in {"obb", "obb_detection", "oriented_detection", "rotated_detection"}:
        return "obb"
    if task in {"seg", "segment", "segmentation", "instance_segmentation"}:
        return "segmentation"
    if task in {"classification", "cls"}:
        return "classification"
    return "detection"


def yolo_task(task_type: str | None) -> str:
    task = normalize_task(task_type)
    if task == "obb":
        return "obb"
    if task == "segmentation":
        return "segment"
    if task == "classification":
        return "classify"
    return "detect"


def resolve_project_path(project_root: Path, value: str | Path) -> Path:
    path = Path(str(value)).expanduser()
    if not path.is_absolute():
        path = project_root / path
    return path.resolve()


def run_command(cmd: list[str] | str, *, cwd: Path, log_file: TextIO | None = None, env: dict[str, str] | None = None) -> None:
    if isinstance(cmd, list):
        display = " ".join(_quote_arg(x) for x in cmd)
        popen_cmd: list[str] | str = cmd
        shell = False
    else:
        display = cmd
        popen_cmd = cmd
        shell = True
    if log_file is not None:
        log_file.write(f"[CMD] {display}\n")
        log_file.flush()
    run_env = os.environ.copy()
    if env:
        run_env.update(env)
    proc = subprocess.Popen(
        popen_cmd,
        cwd=str(cwd),
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1,
        shell=shell,
        env=run_env,
    )
    assert proc.stdout is not None
    for line in proc.stdout:
        if log_file is not None:
            log_file.write(line)
            log_file.flush()
        else:  # pragma: no cover
            print(line, end="", flush=True)
    code = proc.wait()
    if code != 0:
        raise RuntimeError(f"命令执行失败，returncode={code}: {display}")


def _quote_arg(value: str) -> str:
    text = str(value)
    if not text or any(ch.isspace() for ch in text) or any(ch in text for ch in "'\"$`\\"):
        return repr(text)
    return text


def copy_file(src: Path, dst: Path) -> None:
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)


def normalize_env_name(value: Any) -> str:
    """Return an optional conda env name.

    Empty strings, 'none', 'current' and 'base' mean: run in the current process
    environment without `conda run` wrapping.
    """
    text = str(value or "").strip()
    if text.lower() in {"", "none", "current", "base", "false", "0"}:
        return ""
    return text


def conda_run_prefix(ctx: PipelineContext, env_name: str | None) -> list[str]:
    env_name = normalize_env_name(env_name)
    if not env_name:
        return []
    conda = str(ctx.job.get("conda_executable") or os.environ.get("VISIONOPS_CONDA_EXE") or os.environ.get("CONDA_EXE") or "conda")
    return [conda, "run", "--no-capture-output", "-n", env_name]
